### ISSUE TITLE
Rotate Mesh Filter?

### ISSUE THREAD

**Issue by mrweix** [cnr-isti-vclab/meshlabjs#112]
Is there an option or filter to rotate the mesh around a certain axis? In the main Meshlab there is the Manipulator. Is something like this possible in Meshlabjs? Or for a smaller solution: is there something similar like the "Translate Mesh" filter.

**Comment by cignoni** [comment]
yes, sure! manipolators are incoming!

Look at the nice contribs that Antonio ( @nicolettiant89 ) is committing in the antnic89 branch...

**Comment by mrweix** [comment]
The Manipulator tool looks great! I have one question on the move tool in general: 

How can I call the rotate behaviour @nicolettiant89  has implemented in GizmoRotate from another function?
I want to be able to rotate an object by exactly 20 degrees in the x axis for example. Any idea how this could be achieved?

I tried something like this but was without luck.
```
var TransformGizmoRotate=new THREE.TransformGizmoRotate();
TransformGizmoRotate.quaternion.copy( tempQuaternion );
```
