### ISSUE TITLE
Update http://meshlab.sourceforge.net/

### ISSUE THREAD

**Issue by Mannshoch** [cnr-isti-vclab/meshlabjs#116]
Please Update http://meshlab.sourceforge.net/ to inform the user that there isn't any development on it. If that is not true please Update and Inform the user what the actual Roadmap is.

Best regards,
Mannshoch

**Comment by cignoni** [comment]
MeshLab is not dead!
a new release (with a new web site too) is upcoming. 
Have faith.  :)

**Comment by Mannshoch** [comment]
Nice to hear. It was a bit shocking to read these dates here:
![2016-06-06 14_55_07-meshlab - browse files at sourceforge net](https://cloud.githubusercontent.com/assets/7795891/15823397/c4373318-2bfa-11e6-8b54-0ce8423f0c91.png)

Good luck!

**Comment by cignoni** [comment]
You should have looked at this page
https://sourceforge.net/p/meshlab/code/6729/log/?path=/trunk/meshlab

**Comment by Mannshoch** [comment]
I think I got it why every body change from sourceforge to github. :-)

**Comment by Mannshoch** [comment]
@cignoni could you please update README.md with suported filetypes and if posible max sizes ( #118 )

**Comment by idini** [comment]
@Mannshoch  You can find info about supported types through official MeshLab pages. It depends on which version of MeshLab you refer:
- if you refer to MeshLab (Desktop based, to better understand), supported types are listed in the principal page [http://meshlab.sourceforge.net/](url), or if you prefer 

> import:PLY, STL, OFF, OBJ, 3DS, COLLADA, PTX, V3D, PTS, APTS, XYZ, GTS, TRI, ASC, X3D, X3DV, VRML, ALN
export:PLY, STL, OFF, OBJ, 3DS, COLLADA, VRML, DXF, GTS, U3D, IDTF, X3D

- if you refer to MeshLabJS, in Online Documentation at page [http://www.meshlabjs.net/doc/html/core_File.js.html](url) you can find explicit source code that shows supported extension (at line 39); again, if you prefer:

>     SupportedExtensions: {
        OFF: ".off",
        OBJ: ".obj",
        PLY: ".ply",
        STL: ".stl"
    }

**Comment by Mannshoch** [comment]
@idini It was MeshLabJS I was looking for. 
It could be really helpful for many people if these Information could be find more easy.
Also it could be helpful if the Open Dialog in "MeshLabJS" do not show only the "all files" Filetype.
