### ISSUE TITLE
Future of Repair?

### ISSUE THREAD

**Issue by chousemath** [cnr-isti-vclab/meshlabjs#122]
Dear MeshLabJS Team,
Thank you for such a cool project! This is not an issue, but just a question. I was wondering if there were any plans of incorporating the **inverted triangle** and **hole fixing** capabilities of the desktop MeshLab version into the javascript version. Thank you for your time! My apologies if this was not the correct setting to ask this question.

**Comment by cignoni** [comment]
Implemented both features in the two following commits: https://github.com/cnr-isti-vclab/meshlabjs/commit/27cffab168fd33b367a3e1a809e0a155f220dc60 https://github.com/cnr-isti-vclab/meshlabjs/commit/a08ca09d30d18a789e091a73e061e133e7f08c17
