### ISSUE TITLE
Log window short

### ISSUE THREAD

**Issue by cignoni** [cnr-isti-vclab/meshlabjs#2]
In firefox and safary on osx the lower left log window use only the first two lines
(and also the font is different...)
<img width="491" alt="screen shot 2015-07-18 at 12 17 56 pm" src="https://cloud.githubusercontent.com/assets/8055819/8761254/0f4ecf2c-2d47-11e5-89c4-5c36fa7126fa.png">

**Comment by stefanogabriele** [comment]
Fixed by adding "height: 100%" in #mlj-log-widget textarea.
Tested with Firefox and Explorer.
