### ISSUE TITLE
Extract quadric edge collapse from code base

### ISSUE THREAD

**Issue by r03ert0** [cnr-isti-vclab/meshlabjs#67]
Hello,
I have a project that generates meshes using an algorithm similar to marching cubes. I would like to use MeshLabJS's quadric edge collapse filter for decimation right after mesh generation. Would it be possible to extract this filter from the rest of the code base and use it as a 'stand alone' javascript decimator?
thank you!
roberto

**Comment by cignoni** [comment]
Hi, yes it is fairly simple. MeshLabJS is based on the vcg library compiled in javascript through emscpripten. So depending on your language needs you can directly use c++ or js. The c++ code is fairly simple, line 52 of https://github.com/cnr-isti-vclab/meshlabjs/blob/master/sources/Meshing.cpp

Obviously with the usual GPL constraints....
Cheers
P.

**Comment by r03ert0** [comment]
Thank you Paolo,

and is the .js version of the VCG library included in the github repo? (I
haven't been able to find it). That would be very useful!

cheers,
roberto

**Comment by cignoni** [comment]
The js code is not committed in the main branch just becouse it is automatically generated by c++ translation using emscripten. We commit this compiled, unreadable, piece of js (asm.js to be more precise) only in the release branch 

https://github.com/cnr-isti-vclab/meshlabjs/tree/gh-pages/js/generated
cheers
p.
